name    'ft-public_organisation_api'
version '0.0.0'
source 'git@github.com:Financial-Times/public-organisations-api.git'
author 'ft'
license 'Apache License, Version 2.0'
summary 'Provides a public API for users to lookup an organisation'
description 'Public API for retrieving information about an organisation'
project_page 'https://github.com/Financial-Times/public-organisations-api'

## Add dependencies, if any:
dependency 'ft/go_service_profile', '>= 0.0.0'
